language: cpp
sudo: required
distribution: trusty
os:
- linux
- osx
env:
- BADGE=linux
- BADGE=osx
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux

compiler:
- gcc
- clang
branches:
  only:
  - master
  # - "/^v\\d+\\./"

before_install:
- echo "Installing the Testcaser"
- echo "Making Executable Scripts"
- chmod +x ./install.sh && chmod +x ./uninstall.sh
- sudo ./install.sh

script:
- $CXX_FOR_BUILD ./examples/simple-program.cc -std=c++11
- $CXX_FOR_BUILD ./examples/maker_randomBinary.cc -std=c++11
- $CXX_FOR_BUILD ./examples/integrator_virtual-judge.cc -std=c++11
- $CXX_FOR_BUILD ./testcaser/src/main.cc -o virtualjudge
- virtualjudge --version

after_install:
- echo "Removing Testcaser"
- sudo ./uninstall.sh

notifications:
  email: true
  # webhooks:
  #   urls:
  #   on_success: always
  #   on_failure: always
  #   on_start: always


