language: cpp
sudo: required
distribution: trusty
os:
- linux
compiler:
- gcc
- clang
branches:
  only:
  - master
  # - "/^v\\d+\\./"

before_install:
- echo "Installing the Testcaser"
- echo "Making Executable Scripts"
- chmod +x ./unix_install.sh && chmod +x ./unix_uninstall.sh
- sudo ./unix_install.sh

script:
- $CXX_FOR_BUILD ./examples/simple-program.cc -std=c++11

after_install:
- echo "Removing Testcaser"
- sudo ./unix_uninstall.sh

notifications:
  email: true
  # webhooks:
  #   urls:
  #   on_success: always
  #   on_failure: always
  #   on_start: always


