version: 0.4.1.{build}

image:
- Visual Studio 2017

build_script:
- cmd: >-
    cmake -G "Visual Studio 15 2017 Win64" %cd%

    msbuild Tests.sln

artifacts:
- path: .\bin\virtualjudge.exe
  name: virtualjudge